### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by stranak** [ufal/lindat-translation#21]
It took grepping logs to understand that EN/RU and RU/EN models only accept very short input. `INTERNAL SERVER ERROR` message was not that informative. Because the error happened immediately, I actually thought the backend was down.

Please add messages for: 
- [ ] exceeding input size limit
- [ ] backend down

**Comment by kosarko** [comment]
This was a misconfiguration where the backend on `t2t-transformer2` was started with `max_batch_size { value: 5}`, but the frontend is configured with batch size of 20. So on large inputs (where there were more than 5 batches) the backend complained that it's getting more batches than it expects.

This was an exceptional state (as any input =< 100kB should get translated) and logs are generally the place where you should be looking. There should already be an error message for inputs larger than 100kB (the ui shows Translation failed: error REQUEST ENTITY TOO LARGE and you actually get 413 response status)

**Comment by stranak** [comment]
Thanks, looks resolved to me.
