### ISSUE TITLE
Improve mobile UX

### ISSUE THREAD

**Issue by stranak** [ufal/lindat-translation#22]
I propose to remove the "spinning progress bar" animation. Replace it with something like adding dots, or whatever, that is onlz horizontal.

Reason: Current indicator jumps a bit with the content below it. Rather visibly on a mobile device. It also seems to reload the content with each turm, which removes contextual menu. In practice it took some quick reflexes to paste content into the input field on a phone.

**Comment by kosarko** [comment]
I actually thought there already was an issue regarding "mobile" platforms; e.g. some methods of entering text do not "auto submit".

**Comment by kosarko** [comment]
@stranak is the current setup better?

**Comment by stranak** [comment]
Yes, it looks just fine now, thanks. 

Closing the issue.
