### ISSUE TITLE
Pivoting does not work as expected

### ISSUE THREAD

**Issue by martinpopel** [ufal/lindat-translation#23]
I thought that cs->de gives the same result as cs->en->de because we don't have any direct cs->de model.
However, `Jsem student posledního ročníku gymnázia.` with the cs->de option gives `Ich bin Student im letzten Jahr der Gymnastik.`,
but via English we get `I'm a senior in grammar school.` en->de `Ich bin Oberstufenschüler.`

**Comment by kosarko** [comment]
There are cs <-> de marian models by Dominik (@Gldkslfmsd) :

```
{
    "source": ["de"],
    "target": ["cs"],
    "model_framework": "marian",
    "domain": "",
    "model": "de-cs",
    "display": "German->Czech Marian",
    "server": "{MARIAN}:5030",
    "sent_chars_limit": 451,
    "spm_vocab": "marian_data_dir/de-cs/vocab.encs.spm"
  },
  {
    "source": ["cs"],
    "target": ["de"],
    "model_framework": "marian",
    "domain": "",
    "model": "cs-de",
    "display": "Czech->German Marian",
    "server": "{MARIAN}:8030",
    "sent_chars_limit": 433,
    "spm_vocab": "marian_data_dir/cs-de/vocab.encs.spm"
  },
```

**Comment by martinpopel** [comment]
Oh, yes. I forgot. Thanks.
