### ISSUE TITLE
Czech translation improvement

### ISSUE THREAD

**Issue by jirib** [ufal/lindat-translation#33]
English:

```
24-hour protest
```
and translated to Czech:

```
24-hodinový protest
```

But it should be `24hodinový protest` in Czech.

**Comment by martinpopel** [comment]
This stems from our training data, where the usage is mixed (both correct "24hodinový" and [wrong](https://prirucka.ujc.cas.cz/?id=790) "24-hodinový" forms are present in [CzEng](http://ufal.mff.cuni.cz/czeng)).
You may noticed that in other contexts (e.g. "during 24-hour protest" or "Wikipedia in 24-hour blackout protest") it is translated correctly - that's how deep learning works.

While this particular issue would be relatively easy to fix in post-processing, I think such code should not clutter the web service source code (it is Czech specific, quite rare and not urgent, as everyone understands also the incorrect version). We could apply a spell/grammer/typography checker, which would be a more general solution. Unfortunately, the current version of [Korektor](https://lindat.mff.cuni.cz/services/korektor/) does not fix "24-hodinový".

I am thus closing this issue, but I will add it to my list of ideas for improving the translation model (perhaps by processing the training data).
